# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifePlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LifePlayer
  pod 'GCDWebServer/WebUploader', :git => 'https://github.com/lpniuniu/GCDWebServer.git', :branch => 'master', :inhibit_warnings => false
  pod 'Masonry'
  pod 'Bulb', :git => 'https://github.com/lpniuniu/bulb.git', :branch => 'master', :inhibit_warnings => false
  pod 'PINCache'
end
